FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY bin/test-server /server
COPY bin/test-healthcheck /healthcheck
COPY bin/test-sync-instruments /sync-instruments
COPY bin/test-profile-db /profile-db
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/server"]
