import type { Order, Trade } from "@/types";

export const DEMO_ORDERS: Order[] = [
  {
    uuid: "ord-demo-1",
    symbol: "RELIANCE",
    side: "BUY",
    type: "MARKET",
    product: "DELIVERY",
    quantity: 60,
    price_paise: 284000,
    executed_price_paise: 284000,
    status: "EXECUTED",
    created_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
  },
  {
    uuid: "ord-demo-2",
    symbol: "TCS",
    side: "BUY",
    type: "LIMIT",
    product: "DELIVERY",
    quantity: 35,
    price_paise: 409500,
    executed_price_paise: 409500,
    status: "EXECUTED",
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    uuid: "ord-demo-3",
    symbol: "NIFTY24SEPFUT",
    side: "BUY",
    type: "MARKET",
    product: "FNO",
    quantity: 50,
    price_paise: 2332000,
    executed_price_paise: 2332000,
    status: "EXECUTED",
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    uuid: "ord-demo-4",
    symbol: "HDFCBANK",
    side: "BUY",
    type: "LIMIT",
    product: "DELIVERY",
    quantity: 50,
    price_paise: 161000,
    status: "OPEN",
    created_at: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    uuid: "ord-demo-5",
    symbol: "INFY",
    side: "SELL",
    type: "LIMIT",
    product: "INTRADAY",
    quantity: 100,
    price_paise: 189000,
    status: "TRIGGER_PENDING",
    trigger_price_paise: 188500,
    created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    uuid: "ord-demo-6",
    symbol: "TATAMOTORS",
    side: "BUY",
    type: "LIMIT",
    product: "DELIVERY",
    quantity: 100,
    price_paise: 91000,
    status: "CANCELLED",
    created_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
  },
];

export const DEMO_TRADES: Trade[] = [
  {
    uuid: "tr-demo-1",
    order_uuid: "ord-demo-1",
    symbol: "RELIANCE",
    side: "BUY",
    product: "DELIVERY",
    quantity: 60,
    executed_price_paise: 284000,
    executed_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    realized_pnl_paise: 0,
  },
  {
    uuid: "tr-demo-2",
    order_uuid: "ord-demo-2",
    symbol: "TCS",
    side: "BUY",
    product: "DELIVERY",
    quantity: 35,
    executed_price_paise: 409500,
    executed_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    realized_pnl_paise: 0,
  },
  {
    uuid: "tr-demo-3",
    order_uuid: "ord-demo-3",
    symbol: "NIFTY24SEPFUT",
    side: "BUY",
    product: "FNO",
    quantity: 50,
    executed_price_paise: 2332000,
    executed_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    realized_pnl_paise: 425000,
  },
  {
    uuid: "tr-demo-4",
    order_uuid: "ord-demo-prev",
    symbol: "ZOMATO",
    side: "SELL",
    product: "INTRADAY",
    quantity: 200,
    executed_price_paise: 28240,
    executed_at: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    realized_pnl_paise: 148000,
  },
];
