import type { Article } from "@/types";

/**
 * Curated institutional financial wire articles.
 * Used as a dependable baseline when the live Redis ingestion queue is initializing or idle.
 */
export const CURATED_INDIAN_MARKET_NEWS: Article[] = [
  {
    title: "RBI MPC Holds Repo Rate Steady at 6.5%, Highlights Resilient Domestic Growth and Healthy Bank Balance Sheets",
    url: "https://www.rbi.org.in",
    source: "Reserve Bank of India Wire",
    published_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 4,
    symbols: ["NIFTY", "BANKNIFTY"],
    sectors: ["MACRO", "BANKING"],
  },
  {
    title: "Reliance Industries Ramps Up New Energy Solar PV Giga-Complex in Jamnagar, Green Hydrogen Pilots on Track",
    url: "https://www.bseindia.com",
    source: "Exchange Regulatory Filings",
    published_at: new Date(Date.now() - 48 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 3,
    symbols: ["RELIANCE"],
    sectors: ["ENERGY"],
  },
  {
    title: "HDFC Bank Demonstrates Strong Net Interest Income Expansion and Steady CASA Ratio Across Branches",
    url: "https://www.nseindia.com",
    source: "Financial Express Wire",
    published_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 2,
    symbols: ["HDFCBANK", "BANKNIFTY"],
    sectors: ["BANKING"],
  },
  {
    title: "Tata Motors Commercial Vehicle Demerger Approvals Progress, JLR EV Transition Deliveries Exceed Expectations",
    url: "https://www.bseindia.com",
    source: "Mint Markets",
    published_at: new Date(Date.now() - 140 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 3,
    symbols: ["TATAMOTORS"],
    sectors: ["AUTO"],
  },
  {
    title: "TCS Secures Multi-Million Dollar Cloud Modernization Pact with European Financial Conglomerate",
    url: "https://www.nseindia.com",
    source: "Business Standard",
    published_at: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 2,
    symbols: ["TCS", "INFY"],
    sectors: ["IT"],
  },
  {
    title: "Crude Oil Benchmark Volatility Pressures Refining Margins Amid Middle East Supply Chain Re-Routing",
    url: "https://www.reuters.com",
    source: "Global Commodity Wire",
    published_at: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    sentiment: "NEGATIVE",
    score: -2,
    symbols: ["RELIANCE", "NIFTY"],
    sectors: ["ENERGY", "MACRO"],
  },
  {
    title: "Infosys Expands Enterprise Generative AI Portfolio Topaz Across Tier-1 North American Clients",
    url: "https://www.nseindia.com",
    source: "Economic Times Tech",
    published_at: new Date(Date.now() - 310 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 2,
    symbols: ["INFY"],
    sectors: ["IT"],
  },
  {
    title: "Tata Steel European Green Transition Secures Decarbonization Funding Framework, Indian Mills Run Full Capacity",
    url: "https://www.bseindia.com",
    source: "Moneycontrol Pro",
    published_at: new Date(Date.now() - 420 * 60 * 1000).toISOString(),
    sentiment: "NEUTRAL",
    score: 0,
    symbols: ["TATASTEEL"],
    sectors: ["METALS"],
  },
  {
    title: "Zomato Blinkit Quick Commerce Arm Targets 1,000 Dark Stores by Year-End, Path to Sustained EBITDA Profitability",
    url: "https://www.nseindia.com",
    source: "CNBC TV18 Wire",
    published_at: new Date(Date.now() - 550 * 60 * 1000).toISOString(),
    sentiment: "POSITIVE",
    score: 3,
    symbols: ["ZOMATO"],
    sectors: ["MACRO"],
  },
];
